package com.tva.bigbellyblog;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class bigbellyblog {

  private static final Logger logger = LogManager.getLogger(bigbellyblog.class.getName());

  
  public static void bigbellyblogSampleMethod() {
    logger.info("Sample method generated by maven archetype");
    System.out.println("Sample method generated by maven archetype");
  }
}
